import type { FastifyInstance } from "fastify";
import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { authenticateAdmin } from "../middleware/authenticate.js";
import { env } from "../lib/env.js";

const employeeSchema = z.object({
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  email: z.string().email(),
  employeeId: z.string().optional(),
  teamId: z.string().uuid().optional(),
  roleId: z.string().uuid().optional(),
});

export async function employeeRoutes(app: FastifyInstance) {
  app.addHook("preHandler", authenticateAdmin);

  app.get("/", async (request) => {
    const { teamId, status } = request.query as { teamId?: string; status?: string };
    return prisma.employee.findMany({
      where: {
        ...(teamId ? { teamId } : {}),
        ...(status ? { status } : {}),
      },
      include: { team: true, role: true, devices: true },
      orderBy: { firstName: "asc" },
    });
  });

  app.get("/:id", async (request, reply) => {
    const { id } = request.params as { id: string };
    const employee = await prisma.employee.findUnique({
      where: { id },
      include: { team: true, role: true, devices: true },
    });
    if (!employee) return reply.code(404).send({ error: "Employee not found" });
    return employee;
  });

  app.post("/", async (request, reply) => {
    const parsed = employeeSchema.safeParse(request.body);
    if (!parsed.success) return reply.code(400).send(parsed.error.flatten());
    const employee = await prisma.employee.create({ data: parsed.data });
    // installToken is generated by default; this is what gets embedded into that employee's installer.
    return reply.code(201).send(employee);
  });

  app.put("/:id", async (request, reply) => {
    const { id } = request.params as { id: string };
    const parsed = employeeSchema.partial().safeParse(request.body);
    if (!parsed.success) return reply.code(400).send(parsed.error.flatten());
    const employee = await prisma.employee.update({ where: { id }, data: parsed.data });
    return employee;
  });

  app.patch("/:id/status", async (request, reply) => {
    const { id } = request.params as { id: string };
    const { status } = request.body as { status: string };
    if (!["active", "inactive", "deactivated"].includes(status)) {
      return reply.code(400).send({ error: "Invalid status" });
    }
    const employee = await prisma.employee.update({ where: { id }, data: { status } });
    return employee;
  });

  app.delete("/:id", async (request, reply) => {
    const { id } = request.params as { id: string };
    await prisma.$transaction([
      prisma.alertLog.deleteMany({ where: { employeeId: id } }),
      prisma.activityEvent.deleteMany({ where: { employeeId: id } }),
      prisma.screenshot.deleteMany({ where: { employeeId: id } }),
      prisma.device.deleteMany({ where: { employeeId: id } }),
      prisma.employee.delete({ where: { id } }),
    ]);
    await fs.rm(path.join(env.storageDir, "screenshots", id), { recursive: true, force: true });
    return reply.code(204).send();
  });
}
